theme: jekyll-theme-minimal
title: José Ramón García
logo: fotojr.jpeg
description: [Bienvenid@s a mi web minimalista si es que a esto se le puede llamar una web. ;)]
google_analytics:
github:
  is_project_page: false
  
 
